version: "2"

services:
  gunbot:
    container_name: gunbot
    build: gunbot
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - TZ=Europe/Berlin
      - PGID=1024
      - PUID=100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - gunbot_data:/gunbot
      - ./mounts/config.js:/gunbot/config.js
      - ./mounts/logs:/gunbot/logs
      - ./mounts/backups:/gunbot/backups

volumes:
  gunbot_data:
