version: "2"

services:

  nginx-proxy:
    restart: unless-stopped
    image: nginxproxy/nginx-proxy
    container_name: gunbot-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./mounts/nginx/conf:/etc/nginx/conf.d
      - ./mounts/nginx/vhost:/etc/nginx/vhost.d
      - ./mounts/nginx/html:/usr/share/nginx/html
      - ./mounts/nginx/certs:/etc/nginx/certs
      - ./mounts/nginx_custom.conf:/etc/nginx/conf.d/nginx_custom.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-proxy-acme:
    restart: unless-stopped
    image: nginxproxy/acme-companion
    container_name: gunbot-certbot
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=${HOST_EMAIL}

  gunbot:
    container_name: gunbot
    build: gunbot
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    expose:
      - 5000
    environment:
      - VIRTUAL_HOST=${HOST_FQDN}
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=${HOST_FQDN}
      - LETSENCRYPT_EMAIL=${HOST_EMAIL}
      - TZ=${HOST_TIMEZONE}
      - PGID=1024
      - PUID=100
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - gunbot_data:/gunbot
      - ./mounts/config.js:/gunbot/config.js

volumes:
  acme:
  gunbot_data:
